version: v1.0
name: Production Deployment
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Deploy
    task:
      jobs:
        - name: Deploy
          commands:
            - echo "job 1"
